apiVersion: 1

datasources:
  - name: prometheus
    uid: "P1809F7CD0C75ACF3"
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      allowAsRecordingRulesTarget: true
      prometheusType: Prometheus
      prometheusVersion: 3.3.0
      cacheLevel: 'High'
      disableRecordingRules: false
      timeInterval: 5s # Prometheus scrape interval
      incrementalQueryOverlapWindow: 10m